## 1
name: Upload thing when pushing something

on:
  push:
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Set up JDK environment to 8
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 1.8

      # 1
      - name: Checkout code
        uses: actions/checkout@v2
      # 2
      - name: Generate Release APK
        run: ./gradlew android:assembleRelease
      - name: Generate Release JAR
        run: ./gradlew desktop:release
      # 3
      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: android/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Upload as Pre-release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "dev build, ech"
          files: |
              android/build/outputs/apk/release/android-release-unsigned-signed.apk
              desktop/build/libs/*.jar

      - name: Upload to itch.io
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_KEY }}
          CHANNEL: win-linux-mac-stable
          ITCH_GAME: summoning-pixel-dungeon
          ITCH_USER: TrashboxBobylev
          PACKAGE: desktop/build/libs/desktop-*.jar
          VERSION_FILE: version

      - name: Upload to itch.io (android)
        uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_KEY }}
          CHANNEL: android-stable
          ITCH_GAME: summoning-pixel-dungeon
          ITCH_USER: TrashboxBobylev
          PACKAGE: android/build/outputs/apk/release/android-release-unsigned-signed.apk
          VERSION_FILE: version
